CREATE DATABASE bank;
GRANT ALL PRIVILEGES ON DATABASE bank to banker;
\c bank

CREATE TABLE "clients" (
  "client_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "last_name" varchar,
  "user_name" varchar,
  "email" varchar, 
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "accounts" (
  "account_id" int PRIMARY KEY,
  "client_id" int,
  "balance" int,
  "type" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "transactions" (
  "transaction_id"INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_id" int,
  "to_id" int,
  "date_of_t" date,
  "amount" int,
  "type" varchar,
  "created_at" timestamptz DEFAULT 'now()'
);

ALTER TABLE "accounts" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("client_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("from_id") REFERENCES "accounts" ("account_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("to_id") REFERENCES "accounts" ("account_id");
